apiVersion: v1
kind: Pod
metadata:
  name: shared-volumes
spec:
  volumes:
    - name: shared-data
      emptyDir: { }
  containers:
    - name: a
      image: busybox:1.28
      volumeMounts:
        - name: shared-data
          mountPath: /data
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
      stdin: true
      tty: true
    - name: b
      image: busybox:1.28
      volumeMounts:
        - name: shared-data
          mountPath: /data
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
      stdin: true
      tty: true
