apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: shared-data
      emptyDir: { }
  containers:
    - name: shell
      image: busybox:1.28
      volumeMounts:
        - name: shared-data
          mountPath: /data
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
      stdin: true
      tty: true
    - name: shell2
      image: busybox:1.28
      volumeMounts:
        - name: shared-data
          mountPath: /data2
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
      stdin: true
      tty: true
      ports:
        - containerPort: 80
