apiVersion: v1
kind: Pod
metadata:
  name: shared-network
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: curl
    image: krishgobinath/netutils
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    stdin: true
    tty: true     
