apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-as-env
  labels:
    app: secret-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-env
  template:
    metadata:
      labels:
        app: secret-env
    spec:
      containers:
        - name: secret-env
          image: alpine
          command: ["sleep", "3600"]
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: USER_NAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: PASSWORD
