apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-as-env-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: USER_NAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: PASSWORD              
