apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-as-env
  labels:
    app: configmap-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-volumes
  template:
    metadata:
      labels:
        app: configmap-volumes
    spec:
      containers:
        - name: configmap-volumes
          image: alpine
          command: ["sleep", "3600"]
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: demo-configmap
            items:
            - key: "game.properties"
              path: "game.properties"
            - key: "user-interface.properties"
              path: "user-interface.properties"